[package]
name = "fx68k"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
edition = "2018"
license = "GPL"
categories = ["emulators"]

[build-dependencies]
cc = "1.0"

[dependencies]

